/*=============================================================================
	LightFunction.usf: Vertex shader for computing a light function.
	Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"

void Main(
	in float2 InPosition : POSITION,
	out float4 OutScreenPosition : TEXCOORD0,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = OutScreenPosition = float4(InPosition,0,1);
}
