/*=============================================================================
	ScreenPixelShader.usf: Filter pixel shader source.
	Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"

sampler2D Texture;

void Main(
	float2 InUV : TEXCOORD0,
	out float4 OutColor : COLOR0
	)
{
    OutColor = tex2D(Texture, InUV);
}
