/***************************************************************************************/
/*! \file CrosshairCustom3.usf
* 
* Sample custom crosshair file for user made files.
* Requires Crosshair.usf, CrosshairSettings.usf
* 
* 
****************************************************************************************/
{
//code goes here.
//set CROSSHAIR_PIXEL_DRAWN  to 1 if it draws anything. this way the other shapes wont try to draw on the same pixel
}