/*=============================================================================
	OcclusionQueryVertexShader.hlsl: Vertex shader for drawing occlusion queries.
	Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"

void Main(
	in float4 InPosition : POSITION,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = MulMatrix(ViewProjectionMatrix,InPosition);
}
